apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}-lb
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
    component: frontend
  ports:
    {{- if .Values.ipsec.enabled }}
    - name: isakmp
      protocol: UDP
      port: 500
    - name: ipsec-nat-t
      protocol: UDP
      port: 4500
    {{- end }}
    {{- if .Values.wireguard.enabled }}
    - name: wg
      protocol: UDP
      port: {{ .Values.wireguard.port }}
    {{- end }}
