apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: constellation-node-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AutoscalingStrategy is the Schema for the autoscalingstrategies
        API
      displayName: Autoscaling Strategy
      kind: AutoscalingStrategy
      name: autoscalingstrategies.update.edgeless.systems
      version: v1alpha1
    - description: NodeImage is the Schema for the nodeimages API
      displayName: Node Image
      kind: NodeImage
      name: nodeimages.update.edgeless.systems
      version: v1alpha1
    - description: PendingNode is the Schema for the pendingnodes API
      displayName: Pending Node
      kind: PendingNode
      name: pendingnodes.update.edgeless.systems
      version: v1alpha1
    - description: ScalingGroup is the Schema for the scalinggroups API
      displayName: Scaling Group
      kind: ScalingGroup
      name: scalinggroups.update.edgeless.systems
      version: v1alpha1
  description: The constellation node operator manages the lifecycle of constellation
    nodes after cluster initialization. In particular, it is responsible for updating
    the OS images of nodes by replacing nodes running old images with new nodes.
  displayName: Constellation Node Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - update
  - constellation
  links:
  - name: Constellation Node Operator
    url: https://constellation-node-operator.domain
  maintainers:
  - email: mp@edgeless.systems
    name: Malte Poll
  maturity: alpha
  provider:
    name: Edgeless Systems
    url: https://edgeless.systems/
  version: 0.0.0
