# Secrets to use for S3 access.
awsAccessKeyID: "replaceme"
awsSecretAccessKey: "replaceme"
# Pod image to deploy.
image: "ghcr.io/edgelesssys/constellation/s3proxy:v2.19.3"
# Control if multipart uploads are blocked.
allowMultipart: false
# Number of pod replicas to deploy.
replicaCount: 1
