# Namespace to which KMS will be deployed.
namespace: "kube-system"
# Path to which secrets/CMs are mounted.
serviceBasePath: /var/config
# Name of the key within the respective secret that holds the salt.
saltKeyName: salt
# Name of the secret that contains the master secret.
masterSecretName: constellation-mastersecret
# Name of the key within the respective secret that holds the master secret.
masterSecretKeyName: mastersecret
# Name of the ConfigMap that holds the measurements.
measurementsFilename: measurements
