# Build Constellation binaries as quality control
name: Build Constellation binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
  pull_request:
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"

jobs:
  build-bootstrapper:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go environment
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.4"

      - name: Build the bootstrapper
        uses: ./.github/actions/build_bootstrapper

  build-debugd:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go environment
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.4"

      - name: Build debugd
        uses: ./.github/actions/build_debugd

  build-cdbg-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go environment
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.4"

      - name: Build cdbg (Linux, amd64)
        uses: ./.github/actions/build_cdbg
        with:
          targetOS: "linux"
          targetArch: "amd64"

      - name: Build cdbg (Linux, arm64)
        uses: ./.github/actions/build_cdbg
        with:
          targetOS: "linux"
          targetArch: "arm64"

  build-cdbg-macos:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go environment
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.4"
      - name: Build cdbg (macOS, amd64)
        uses: ./.github/actions/build_cdbg
        with:
          targetOS: "darwin"
          targetArch: "amd64"

      - name: Build cdbg (macOS, arm64)
        uses: ./.github/actions/build_cdbg
        with:
          targetOS: "darwin"
          targetArch: "arm64"

  build-disk-mapper:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go environment
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.4"
      - name: Build disk-mapper
        uses: ./.github/actions/build_disk_mapper

  build-cli-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go environment
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.4"

      - name: Build CLI (Linux, amd64)
        uses: ./.github/actions/build_cli
        with:
          targetOS: linux
          targetArch: amd64

      - name: Build CLI (Linux, arm64)
        uses: ./.github/actions/build_cli
        with:
          targetOS: linux
          targetArch: arm64

  build-cli-macos:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Go environment
        uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.4.0
        with:
          go-version: "1.19.4"

      - name: Build CLI (macOS, amd64)
        uses: ./.github/actions/build_cli
        with:
          targetOS: darwin
          targetArch: amd64

      - name: Build CLI (macOS, arm64)
        uses: ./.github/actions/build_cli
        with:
          targetOS: darwin
          targetArch: arm64
