name: Build and upload libvirt image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "cli/internal/libvirt/**"
      - "!internal/versions/versions.go" # Don't build on version bumps to avoid infinite loops
      - ".github/workflows/build-libvirt-image.yml"

jobs:
  build-qemu-metadata-api:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ !github.event.pull_request.head.repo.fork && github.head_ref || '' }}

      - name: Build and upload libvirt container image
        id: build-and-upload
        uses: ./.github/actions/build_micro_service
        with:
          name: "libvirt"
          dockerfile: "cli/internal/libvirt/Dockerfile"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          cosignPublicKey: ${{ startsWith(github.ref, 'refs/heads/release/v') && secrets.COSIGN_PUBLIC_KEY || secrets.COSIGN_DEV_PUBLIC_KEY }}
          cosignPrivateKey: ${{ startsWith(github.ref, 'refs/heads/release/v') && secrets.COSIGN_PRIVATE_KEY || secrets.COSIGN_DEV_PRIVATE_KEY }}
          cosignPassword: ${{ startsWith(github.ref, 'refs/heads/release/v') && secrets.COSIGN_PASSWORD || secrets.COSIGN_DEV_PASSWORD }}
