name: Build and upload all apko container images

on:
  workflow_dispatch:

jobs:
  build-apko-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          ref: ${{ github.head_ref }}

      - name: Build and upload apko image
        uses: ./.github/actions/build_apko
        with:
          registry: ghcr.io
          githubToken: ${{ secrets.GITHUB_TOKEN }}
