name: Pseudo-Version tool freshness check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - renovate/*


jobs:
  check-freshness:
    name: Pseudo-Version tool freshness check
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false

      - name: Check freshness
        shell: bash
        run: |
            bazel run //bazel/ci:pseudo_version_tool_freshness
