# This workflow check
name: Operator code generation check

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "operators/**"
      - "./.github/workflows/test-operator-codegen.yml"
  pull_request:
    paths:
      - "operators/**"
      - "./.github/workflows/test-operator-codegen.yml"

jobs:
  govulncheck:
    name: check-codegen
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ !github.event.pull_request.head.repo.fork && github.head_ref || '' }}

      - name: Setup Go environment
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: "1.23.2"
          cache: true

      - name: Run code generation
        shell: bash
        working-directory: "operators/"
        run: |
          dirs=$(find . \! -name . -prune -type d)
          for dir in $dirs; do
            (cd "$dir"; make manifests generate)
          done

      - name: Check diff and fail on changes
        shell: bash
        run: git diff --exit-code
