name: Bazel unit tests and linting

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "**.bzl"
      - "**.bazel"
      - ".github/workflows/test-bazel.yml"
  pull_request:
    paths:
      - "**.bzl"
      - "**.bazel"
      - ".github/workflows/test-bazel.yml"

jobs:
  bazel-test:
    name: Bazel tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ !github.event.pull_request.head.repo.fork && github.head_ref || '' }}

      - name: Run buildifier
        shell: bash
        run: |
          bazelisk test //:buildifier-check

      # TODO(malt3): Find workflows to run bazel unit tests
      # - name: Run unit tests
      #   shell: bash
      #   run: bazelisk test --test_output=all ...
